version: "3"
services:
  squid-alpine-ssl:
    build: .
    environment:
      - CN=squid.local
      - O=squid
      - OU=squid
      - C=US
    ports:
      - "3128:3128"
      - "4128:4128"
    volumes:
      - ./log:/var/log/
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/cache
      - ./cert:/etc/squid-cert
      - ./lib:/usr/local/lib
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"